//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSale
    {
        public int IdDetailSale { get; set; }
        public int IdProduct { get; set; }
        public int Count { get; set; }
        public int DetailSale_IdSale { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual Product Product { get; set; }
    }
}
